//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XadesNetLib.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XadesNetLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema targetNamespace=&quot;http://uri.etsi.org/01903/v1.3.2#&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://uri.etsi.org/01903/v1.3.2#&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xsd:import namespace=&quot;http://www.w3.org/2000/09/xmldsig#&quot; schemaLocation=&quot;http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd&quot;/&gt;
        ///	&lt;!-- Start auxiliary types definitions: AnyType, ObjectIdentifierType, 
        ///Encapsulated [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string XAdES_1_3_2 {
            get {
                return ResourceManager.GetString("XAdES_1_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE schema
        ///  PUBLIC &quot;-//W3C//DTD XMLSchema 200102//EN&quot; &quot;http://www.w3.org/2001/XMLSchema.dtd&quot;
        /// [
        ///   &lt;!ATTLIST schema 
        ///     xmlns:ds CDATA #FIXED &quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
        ///   &lt;!ENTITY dsig &apos;http://www.w3.org/2000/09/xmldsig#&apos;&gt;
        ///   &lt;!ENTITY % p &apos;&apos;&gt;
        ///   &lt;!ENTITY % s &apos;&apos;&gt;
        ///  ]&gt;
        ///
        ///&lt;!-- Schema for XML Signatures
        ///    http://www.w3.org/2000/09/xmldsig#
        ///    $Revision: 1.1 $ on $Date: 2002/02/08 20:32:26 $ by $Author: reagle $
        ///
        ///    Copyright 2001 The Internet Societ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string xmldsig_core_schema {
            get {
                return ResourceManager.GetString("xmldsig_core_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!-- DTD for XML Schemas: Part 1: Structures
        ///     Public Identifier: &quot;-//W3C//DTD XMLSCHEMA 200102//EN&quot;
        ///     Official Location: http://www.w3.org/2001/XMLSchema.dtd --&gt;
        ///&lt;!-- $Id: XMLSchema.dtd,v 1.31 2001/10/24 15:50:16 ht Exp $ --&gt;
        ///&lt;!-- Note this DTD is NOT normative, or even definitive. --&gt;           &lt;!--d--&gt;
        ///&lt;!-- prose copy in the structures REC is the definitive version --&gt;    &lt;!--d--&gt;
        ///&lt;!-- (which shouldn&apos;t differ from this one except for this --&gt;         &lt;!--d--&gt;
        ///&lt;!-- comment and entity expansio [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string XMLSchema {
            get {
                return ResourceManager.GetString("XMLSchema", resourceCulture);
            }
        }
    }
}
